/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NEXTID_H_RPCGEN
#define _NEXTID_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define NEXT_ID 2
#define VER_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define nextid 0
extern  int * nextid_1(void *, CLIENT *);
extern  int * nextid_1_svc(void *, struct svc_req *);
extern int next_id_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define nextid 0
extern  int * nextid_1();
extern  int * nextid_1_svc();
extern int next_id_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NEXTID_H_RPCGEN */